import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useAppStore } from '@/store/useAppStore'
import { useTranslation } from '@/lib/translations'
import AuroraBackground from '@/components/ui/AuroraBackground'
import { format } from 'date-fns'
import toast from 'react-hot-toast'

function VerificationStep({ onVerify }) {
  const [step,    setStep]    = useState(0)
  const [address, setAddress] = useState('')

  const handleLookup = () => {
    if (!address.trim()) { toast.error('Enter a wallet address.'); return }
    setStep(1)
    setTimeout(() => { setStep(2); setTimeout(() => onVerify(address.trim()), 800) }, 1600)
  }

  return (
    <div className="text-center space-y-6">
      <div
        className="w-20 h-20 rounded-full mx-auto flex items-center justify-center text-4xl"
        style={{ background: 'rgba(11,43,38,0.3)', border: '2px solid rgba(218,241,222,0.2)' }}
      >
        🕊️
      </div>

      {step === 0 && (
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
          <input
            className="vault-input text-center"
            placeholder="0x… wallet address of the person"
            value={address}
            onChange={(e) => setAddress(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleLookup()}
          />
          <button onClick={handleLookup} className="btn-primary w-full">
            Look up legacy
          </button>
        </motion.div>
      )}

      {step === 1 && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center gap-4">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
            className="w-10 h-10 rounded-full border-2 border-t-transparent"
            style={{ borderColor: '#8EB69B', borderTopColor: 'transparent' }}
          />
          <p className="font-inter text-sm" style={{ color: '#8EB69B' }}>
            Verifying on-chain identity…
          </p>
        </motion.div>
      )}

      {step === 2 && (
        <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="text-center">
          <span className="text-4xl">✓</span>
          <p className="font-sora font-semibold mt-2" style={{ color: '#4a9e6a' }}>Identity verified.</p>
        </motion.div>
      )}
    </div>
  )
}

function ReleasePortal({ claimedAddress }) {
  const { capsules, profileFiles, displayName, walletAddress, legacySettings } = useAppStore()

  // Use real store data — capsules and files from the vault
  const portalCapsules = capsules.slice(0, 6)
  const allFiles = Object.values(profileFiles || {}).flat()
  const portalFiles = allFiles.slice(0, 8)

  const shortAddr = claimedAddress
    ? `${claimedAddress.slice(0, 6)}…${claimedAddress.slice(-4)}`
    : walletAddress
      ? `${walletAddress.slice(0, 6)}…${walletAddress.slice(-4)}`
      : '0x????…????'

  const [openCapsule, setOpenCapsule] = useState(null)
  const [claimed,     setClaimed]     = useState(false)

  const totalPhotos = capsules.reduce((s, c) => s + (c.photos || 0), 0)
  const totalVoice  = capsules.reduce((s, c) => s + (c.voice  || 0), 0)
  const totalLetters = capsules.reduce((s, c) => s + (c.letters || 0), 0)

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-8"
    >
      {/* Header */}
      <div className="text-center">
        <div className="text-5xl mb-4">🕊️</div>
        <h2 className="font-sora font-bold text-2xl mb-2" style={{ color: '#DAF1DE' }}>
          They left this for you.
        </h2>
        <p className="font-inter text-sm" style={{ color: '#8EB69B' }}>
          From: {displayName || 'Anonymous'} · {shortAddr}<br />
          Released: {format(new Date(), 'dd MMMM yyyy')}
        </p>
      </div>

      {/* AI Memory Portrait */}
      <div className="glass-card p-6" style={{ borderColor: 'rgba(142,182,155,0.3)' }}>
        <div className="flex items-center gap-3 mb-4">
          <span className="badge-cobalt">AI Memory Portrait</span>
          <span className="font-inter text-xs" style={{ color: '#8EB69B' }}>Generated by Claude</span>
        </div>
        <p className="font-inter text-sm leading-relaxed" style={{ color: '#DAF1DE' }}>
          "{displayName || 'This person'} left behind a carefully curated vault spanning {capsules.length} memory capsule{capsules.length !== 1 ? 's' : ''}{totalPhotos > 0 ? `, ${totalPhotos} photograph${totalPhotos !== 1 ? 's' : ''}` : ''}{totalVoice > 0 ? `, ${totalVoice} voice recording${totalVoice !== 1 ? 's' : ''}` : ''}${totalLetters > 0 ? `, and ${totalLetters} personal letter${totalLetters !== 1 ? 's' : ''}` : ''}. Every item was encrypted and stored on-chain — immutable, permanent, and meant only for you. This vault is their final act of keeping everyone close."
        </p>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { icon: '🌸', value: capsules.length, label: 'Capsules' },
          { icon: '📎', value: allFiles.length, label: 'Files' },
          { icon: '💌', value: totalLetters + totalVoice, label: 'Messages' },
        ].map((s, i) => (
          <div key={i} className="glass-card p-4 text-center">
            <div className="text-2xl mb-1">{s.icon}</div>
            <div className="font-sora font-bold text-xl" style={{ color: '#DAF1DE' }}>{s.value}</div>
            <div className="font-inter text-xs" style={{ color: '#8EB69B' }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* Capsules */}
      {portalCapsules.length > 0 && (
        <div>
          <h3 className="font-sora font-semibold text-lg mb-4" style={{ color: '#DAF1DE' }}>
            Memory Capsules
          </h3>
          <div className="space-y-3">
            {portalCapsules.map((capsule, i) => (
              <motion.div
                key={capsule.id}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.1 }}
                className="glass-card p-4 cursor-pointer"
                onClick={() => setOpenCapsule(openCapsule === capsule.id ? null : capsule.id)}
              >
                <div className="flex items-center gap-4">
                  <div
                    className="w-12 h-12 rounded-xl flex items-center justify-center text-xl"
                    style={{ background: 'rgba(11,43,38,0.4)' }}
                  >
                    {capsule.type === 'Legacy' ? '🕊️' : capsule.type === 'Time-locked' ? '⏰' : '💌'}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-sora font-semibold text-sm" style={{ color: '#DAF1DE' }}>
                      {capsule.title}
                    </h4>
                    <div className="flex gap-3 mt-1 flex-wrap">
                      {capsule.photos > 0 && <span className="text-xs" style={{ color: '#8EB69B' }}>📸 {capsule.photos}</span>}
                      {capsule.voice  > 0 && <span className="text-xs" style={{ color: '#8EB69B' }}>🎙️ {capsule.voice}</span>}
                      {capsule.letters > 0 && <span className="text-xs" style={{ color: '#8EB69B' }}>💌 {capsule.letters}</span>}
                      <span className="text-xs" style={{ color: 'rgba(142,182,155,0.4)' }}>{capsule.type}</span>
                    </div>
                  </div>
                  <span style={{ color: '#8EB69B' }}>{openCapsule === capsule.id ? '▲' : '▼'}</span>
                </div>

                <AnimatePresence>
                  {openCapsule === capsule.id && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="mt-4 pt-4" style={{ borderTop: '1px solid rgba(218,241,222,0.1)' }}>
                        <p className="font-inter text-sm mb-4" style={{ color: '#8EB69B' }}>
                          {capsule.contentPreview}
                        </p>
                        {capsule.unlockDate && (
                          <p className="font-inter text-xs mb-3 flex items-center gap-1" style={{ color: 'rgba(142,182,155,0.5)' }}>
                            ⏰ Unlocks {format(new Date(capsule.unlockDate), 'dd MMM yyyy')}
                          </p>
                        )}
                        <div className="flex gap-2 flex-wrap">
                          {capsule.photos > 0 && (
                            <button className="text-sm px-4 py-2 rounded-lg" onClick={(e) => { e.stopPropagation(); toast.success('Loading photos…') }} style={{ background: 'rgba(11,43,38,0.4)', color: '#DAF1DE' }}>
                              View {capsule.photos} photo{capsule.photos !== 1 ? 's' : ''}
                            </button>
                          )}
                          {capsule.voice > 0 && (
                            <button
                              onClick={(e) => { e.stopPropagation(); toast.success('Playing voice note…') }}
                              className="text-sm px-4 py-2 rounded-lg"
                              style={{ background: 'rgba(209,96,31,0.2)', color: '#D1601F' }}
                            >
                              ▶ Play voice notes
                            </button>
                          )}
                          {capsule.letters > 0 && (
                            <button onClick={(e) => { e.stopPropagation(); toast.success('Opening letters…') }} className="text-sm px-4 py-2 rounded-lg" style={{ background: 'rgba(142,182,155,0.2)', color: '#8EB69B' }}>
                              Read letters
                            </button>
                          )}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      )}

      {/* Documents & Assets */}
      {portalFiles.length > 0 && (
        <div>
          <h3 className="font-sora font-semibold text-lg mb-4" style={{ color: '#DAF1DE' }}>
            Documents & Files
          </h3>
          <div className="space-y-2">
            {portalFiles.map((file) => (
              <div key={file.id} className="glass-card p-4 flex items-center gap-3">
                <span className="text-xl">{file.type === 'pdf' ? '📄' : file.type === 'jpg' || file.type === 'png' ? '🖼️' : '📎'}</span>
                <div className="flex-1 min-w-0">
                  <p className="font-inter text-sm truncate" style={{ color: '#DAF1DE' }}>{file.name}</p>
                  <p className="font-inter text-xs" style={{ color: '#8EB69B' }}>{file.size} · {file.nftId}</p>
                </div>
                <button
                  onClick={() => toast.success('Downloading file…')}
                  className="text-sm px-3 py-1.5 rounded-lg flex-shrink-0"
                  style={{ background: 'rgba(218,241,222,0.15)', color: '#DAF1DE' }}
                >
                  Download
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Final message */}
      {legacySettings.finalMessage?.length > 0 && (
        <div className="glass-card p-6" style={{ borderColor: 'rgba(142,182,155,0.25)' }}>
          <div className="flex items-center gap-2 mb-4">
            <span className="text-xl">💌</span>
            <h3 className="font-sora font-semibold" style={{ color: '#DAF1DE' }}>Final Message</h3>
          </div>
          <p className="font-inter text-sm leading-relaxed italic" style={{ color: '#8EB69B' }}>
            "{legacySettings.finalMessage}"
          </p>
        </div>
      )}

      {/* Claim crypto */}
      <div className="glass-card p-6 text-center" style={{ borderColor: 'rgba(142,182,155,0.3)' }}>
        <h3 className="font-sora font-bold text-xl mb-2" style={{ color: '#8EB69B' }}>
          Claim crypto assets
        </h3>
        <p className="font-inter text-sm mb-4" style={{ color: '#8EB69B' }}>
          Estimated value: 0.42 ETH · 2,100 MATIC
        </p>
        {!claimed ? (
          <button
            onClick={() => { setClaimed(true); toast.success('Transfer initiated on-chain.') }}
            className="btn-cobalt text-base px-8"
          >
            Claim to my wallet
          </button>
        ) : (
          <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="space-y-2">
            <p className="text-3xl">✅</p>
            <p className="font-sora font-semibold" style={{ color: '#4a9e6a' }}>Transfer initiated. Funds arriving in 2–5 minutes.</p>
          </motion.div>
        )}
      </div>
    </motion.div>
  )
}

export default function ClaimPage() {
  const { lang } = useAppStore()
  const tr = useTranslation(lang)
  const [verified,       setVerified]       = useState(false)
  const [claimedAddress, setClaimedAddress] = useState('')

  return (
    <div className="relative min-h-screen flex flex-col items-center justify-start py-16 px-4" style={{ paddingTop: '80px' }}>
      <AuroraBackground />

      <div className="relative z-10 w-full max-w-2xl">
        {!verified ? (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass-card p-8"
          >
            <div className="text-center mb-8">
              <h1 className="font-sora font-bold text-2xl mb-2" style={{ color: '#DAF1DE' }}>
                {tr('claim.title')}
              </h1>
              <p className="font-inter text-sm" style={{ color: '#8EB69B' }}>
                {tr('claim.subtitle')}
              </p>
            </div>
            <VerificationStep onVerify={(addr) => { setClaimedAddress(addr); setVerified(true) }} />
          </motion.div>
        ) : (
          <ReleasePortal claimedAddress={claimedAddress} />
        )}
      </div>
    </div>
  )
}
